title: Notes on JavaParser
email: hexagonaal@gmail.com
baseurl: ""
url: "https://matozoid.github.io"
twitter_username: matozoid
github_username:  matozoid

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
